/**
 * Ehime spots — now backed by REAL data sourced from OpenStreetMap.
 *
 * The dataset is generated by `scripts/fetch-spots.mjs` into
 * `ehime-spots.generated.ts` (names + coordinates from OSM). This module simply
 * re-exports it so every existing importer of `EHIME_SPOTS` gets the real data
 * unchanged.
 *
 * Data © OpenStreetMap contributors, licensed under the ODbL. Attribution must
 * be shown wherever this data is displayed (the map credits OSM for tiles).
 * OSM provides no reviews and rarely descriptions, so `reviews` is empty and
 * `localizedDescriptions` is a light name-based line.
 *
 * To refresh the data: `node scripts/fetch-spots.mjs`.
 */

export { EHIME_SPOTS } from "./ehime-spots.generated";
