/**
 * Ehime spots — now backed by REAL data sourced from OpenStreetMap.
 *
 * The dataset is generated by `scripts/fetch-spots.mjs` into
 * `ehime-spots.generated.ts` (names + coordinates from OSM). This module simply
 * re-exports it so every existing importer of `EHIME_SPOTS` gets the real data
 * unchanged.
 *
 * Data © OpenStreetMap contributors, licensed under the ODbL. Attribution must
 * be shown wherever this data is displayed (the map credits OSM for tiles).
 * OSM provides no reviews and rarely descriptions, so `reviews` is empty and
 * `localizedDescriptions` is a light name-based line.
 *
 * To refresh the data: `node scripts/fetch-spots.mjs`.
 */

import type { Spot } from "../../ports";
import { EHIME_SPOTS as GENERATED } from "./ehime-spots.generated";
import { EHIME_FOOD_CURATED } from "./ehime-food.curated";

/**
 * The full spot catalogue: real OSM data (attractions, onsen, souvenirs, and a
 * few local-food matches) plus a curated set of well-known Ehime 郷土料理 shops
 * so the グルメ layer represents 鯛めし・三津浜焼き・焼豚玉子飯・みかん 等.
 */
export const EHIME_SPOTS: Spot[] = [...GENERATED, ...EHIME_FOOD_CURATED];
